### ISSUE TITLE
Rewrite interface of AssociatedTask

### ISSUE THREAD

**Issue by Trulsaa** [Alv-no/AlvTime-WebApi#135]

**Comment by Trulsaa** [comment]
POST CreateAssosiatedTask -> POST AssosiatedTasks
POST UpdateAssosiatedTask -> PUT AssosiatedTasks

**Comment by palbock** [comment]
Need to update business logic as well, to take List as parameter and iterate over each task.
[FromBody] AssociatedTaskRequestDto associatedTask -> [FromBody] IEnumerable<AssociatedTaskRequestDto> associatedTasks
Wrap create and update Associated Tasks in foreach
